import matplotlib.pyplot as plt
import numpy as np


def plot_points_2d(pltp, in_points):
    """plots in_points (points generated by mcmc that are inside pltp) (red) and a circle (blue)
    with centre (0, 0) and biggest radius such that it doesn't cross pltp's edges
    """
    fig, ax = plt.subplots()
    ax.set_aspect(1)
    ax.set_xlim(-1, 1)
    ax.set_ylim(-1, 1)
    plt.plot(
        np.array([arr[0] for arr in in_points]),
        np.array([arr[1] for arr in in_points]),
        "o",
        color="red",
        zorder=1,
    )
    ax.add_patch(
        plt.Circle(
            (0, 0),
            pltp.maximum_radius_to_fit(),
            color="b",
            zorder=2,
            fill=False,
            linewidth=3,
        )
    )

    plt.show()
